name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        docker build . --file ./images/html-validator/Dockerfile --tag docker.pkg.github.com/yoriiis/docker-hub/html-validator:v1
        docker login docker.pkg.github.com --username yoriiis --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/yoriiis/docker-hub/html-validator:v1
        
